# Reference Material
#
# * https://www.podcast.co/create/podcast-rss-feeds

title = "Chats with James Podcast"
description = """
Chats with James is a podcast discussing everything \
that James or his guests are passionate about.

Embedded Systems, the Rust Programming Language, and \
a variety of other technical topics are the most commonly \
discussed items.

New episodes are released every Tuesday.
"""
subtitle = "James Munns talks to guests about things they are passionate about"
website = "https://jamesmunns.com/podcast/"
language = "en-us"
copyright = "2020"
webmaster = "contact@onevariable.com (James Munns)"
managing-editor = "contact@onevariable.com (James Munns)"

author = "James Munns"
author-email = "contact@onevariable.com"

formats = [
    "flac",
    "mp3",
    "m4a",
]
hosting-base-url = "https://delivery.jamescdn.com"
explicit = false
keywords = [
    "rust",
    "programming",
    "technology"
]

# TODO - support subcategories?
category = "Technology"

[logo]
url = "https://delivery.jamescdn.com/logo2.png"
title = "Chats with James Podcast"
link = "https://jamesmunns.com/podcast/"

[[episodes]]
title = "007 - Michael Nitschinger"
url = "https://jamesmunns.com/podcast/007-michael/"
description = """
James chats with Michael Nitschinger of Couchbase to discuss Coffee \
Machines, PID control loops, Bluetooth Low Energy, and Databases.
"""
subtitle = "James chats with Michael Nitschinger of Couchbase"
files = [
    "2021-02-09-michael-nitschinger.m4a",
    "2021-02-09-michael-nitschinger.mp3",
    "2021-02-09-michael-nitschinger.flac",
]
duration = "00:53:08"
publish-date = "Tue, 09 Feb 2021 11:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "engineering",
    "Rust",
    "coffee",
    "espresso",
    "control systems",
    "databases",
]

[[episodes]]
title = "006 - Bryan Cantrill"
url = "https://jamesmunns.com/podcast/006-bryan/"
description = """
James chats with Bryan Cantrill of Oxide Computer to discuss the \
open source hardware explosion, Oxide's experience with Embedded Rust, \
the importance of a culture of sharing knowledge, and the joy of fixing \
hard-to-diagnose systems problems.
"""
subtitle = "James chats with Bryan Cantrill of Oxide Computer Company"
files = [
    "2021-02-02-bryan-cantrill.m4a",
    "2021-02-02-bryan-cantrill.mp3",
    "2021-02-02-bryan-cantrill.flac",
]
duration = "01:24:22"
publish-date = "Tue, 02 Feb 2021 16:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "engineering",
    "Rust",
    "systems engineering",
    "open source",
]

[[episodes]]
title = "005 - Clifford Heath"
url = "https://jamesmunns.com/podcast/005-clifford/"
description = """
James chats with Clifford Heath to \
discuss the differences between procedural and structural code, using \
natural language processing to describe software, code generation, \
and programming education approaches.
"""
subtitle = "James chats with Clifford Heath"
files = [
    "2021-01-26-clifford-heath.m4a",
    "2021-01-26-clifford-heath.mp3",
    "2021-01-26-clifford-heath.flac",
]
duration = "01:04:45"
publish-date = "Tue, 26 Jan 2021 14:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "engineering",
    "schemas",
    "natural language",
]

[[episodes]]
title = "004 - François Baldassari"
url = "https://jamesmunns.com/podcast/004-francois/"
description = """
James chats with François Baldassari to discuss embedded systems, \
engineering practices (and where the industry is lacking), and the \
social side of improving the skills of embedded systems teams.
"""
subtitle = "James chats with François Baldassari of Memfault"
files = [
    "2021-01-19-francois-baldassari.m4a",
    "2021-01-19-francois-baldassari.mp3",
    "2021-01-19-francois-baldassari.flac",
]
duration = "00:48:36"
publish-date = "Tue, 19 Jan 2021 06:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "embedded",
    "embedded systems",
    "software quality",
    "engineering",
]

[[episodes]]
title = "003 - Michael Gattozzi"
url = "https://jamesmunns.com/podcast/003-michael/"
description = """
James chats with Michael Gattozzi to discuss developer tooling, message \
serialization, and undefined behavior in Rust.
"""
subtitle = "James chats with Michael Gattozzi"
files = [
    "2021-01-12-michael-gattozzi.m4a",
    "2021-01-12-michael-gattozzi.mp3",
    "2021-01-12-michael-gattozzi.flac",
]
duration = "01:11:28"
publish-date = "Tue, 12 Jan 2021 06:00:00 GMT"
keywords = [
    "rust",
    "programming",
    "technology",
    "serialization",
]

[[episodes]]
title = "002 - Christopher Hunt"
url = "https://jamesmunns.com/podcast/002-chris/"
description = """
James chats with Christopher Hunt to discuss programming languages, \
the cost of software abstraction, Bluetooth, and state machines.
"""
subtitle = "James chats with Christopher Hunt"
files = [
    "2021-01-05-christopher-hunt.m4a",
    "2021-01-05-christopher-hunt.mp3",
    "2021-01-05-christopher-hunt.flac",
]
duration = "01:11:47"
publish-date = "Tue, 05 Jan 2021 16:00:00 GMT"
keywords = [
    "rust",
    "programming",
    "technology",
]

[[episodes]]
title = "001 - Lachezar Lechev"
url = "https://jamesmunns.com/podcast/001-lachezar/"
description = """
James chats with Lachezar Lechev to discuss Rust in Avionics, \
drone simulation technologies, and burnout in software development.
"""
subtitle = "James chats with Lachezar Lechev"
files = [
    "2020-12-29-lachezar-lechev.m4a",
    "2020-12-29-lachezar-lechev.mp3",
    "2020-12-29-lachezar-lechev.flac",
]
duration = "00:45:35"
publish-date = "Tue, 29 Dec 2020 19:00:00 GMT"
keywords = [
    "avionics",
    "rust",
    "programming",
    "technology"
]

[[episodes]]
title = "000 - Foreward"
url = "https://jamesmunns.com/podcast/000-foreward/"
description = "James introduces the Chats with James Podcast."
subtitle = "James introduces the Chats with James Podcast."
files = [
    "2020-12-28-introduction.flac",
    "2020-12-28-introduction.mp3",
    "2020-12-28-introduction.m4a",
]
duration = "00:01:13"
publish-date = "Mon, 28 Dec 2020 19:00:00 GMT"
keywords = [
    "rust",
    "programming",
    "technology"
]
